#
# config.py -- Mozilla-devel build configuration file
#
# Note: This file is automatically generated by "build configure". Your
# changes will be lost the next time that is run.
#
# See "build -h configure" for details.

blessed = False
buildDir = '/home/lc/projekty/OpenKomodoIDE/build'
buildOpt = []
buildTag = None
buildType = 'release'
changenum = 0
compiler = None
configureOptions = ['-k', '14.0']
enableMar = True
gcc = '/bin/gcc'
gxx = '/bin/g++'
jsStandalone = False
komodoCommaVersion = '14,0'
komodoUndottedVersion = '140'
komodoVersion = '14.0'
mozBuildExtensions = []
mozObjDir = 'obj-x86_64-pc-linux-gnu'
mozSrcGitRev = '14000'
mozSrcName = 'moz14000'
mozSrcScheme = '14000'
mozSrcType = 'git'
mozVer = 140.0
mozconfig = "# Options for 'configure' (same as command-line options).\nmk_add_options MOZ_OBJDIR=obj-x86_64-pc-linux-gnu\nmk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-x86_64-pc-linux-gnu\nexport CC=/bin/gcc\nexport CXX=/bin/g++\nac_add_options --enable-linker=gold\nac_add_options --disable-tests\nac_add_options --enable-optimize\nac_add_options --disable-debug\nac_add_options --enable-application=komodo\n"
patchesDirs = ['patches-new']
platform = 'linux-x86_64'
platinfo = {'os': 'linux', 'os_ver': '5.15.0', 'arch': 'x86_64', 'distro': 'Debian', 'distro_desc': 'Debian GNU/Linux 12 (bookworm)', 'distro_ver': '12', 'distro_codename': 'bookworm', 'libcpp': 'libcpp6', 'libc': 'libc6', 'glibc': 'glibc', 'glibc_ver': '2.36', 'name': 'linux-x86_64'}
pyVer = '3.11'
python = '/bin/python3'
pythonVersion = '3.11'
srcTreeName = 'moz14000-ko14.0'
stripBuild = False
universal = False
withCrashReportSymbols = False
withPGOCollection = False
withPGOGeneration = False
